name: Laravel Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.1', '8.2']

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit

    - name: Install dependencies
      run: composer install --working-dir=tp-engsoft --prefer-dist --no-progress --no-suggest

    - name: Create .env file
      run: cp tp-engsoft/.env.example tp-engsoft/.env
      shell: bash

    - name: Generate application key
      run: php tp-engsoft/artisan key:generate

    - name: Configure environment
      run: |
        php tp-engsoft/artisan config:cache
        php tp-engsoft/artisan route:cache
        php tp-engsoft/artisan view:cache

    - name: Set up database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php tp-engsoft/artisan migrate --force

    - name: Run tests
      run: php tp-engsoft/artisan test
