name: Laravel Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.1', '8.2']

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tp_engsoft
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit

    - name: Install dependencies
      run: composer install --working-dir=tp-engsoft --prefer-dist --no-progress --no-suggest

    - name: Create .env file
      run: cp tp-engsoft/.env.example tp-engsoft/.env
      shell: bash

    - name: Update .env for MySQL service
      run: |
        sed -i 's/DB_HOST=.*/DB_HOST=mysql/' tp-engsoft/.env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=tp_engsoft/' tp-engsoft/.env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' tp-engsoft/.env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' tp-engsoft/.env
      shell: bash

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          if php tp-engsoft/artisan migrate --force; then
            break
          fi
          echo 'Waiting for MySQL to be ready...'
          sleep 1
        done

    - name: Run tests
      run: |
          php tp-engsoft/artisan test

